"""initial_schema

Revision ID: d7018b495f15
Revises: 
Create Date: 2026-09-03 03:22:36.240964
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd7018b495f15'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('run_type', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('decision_log', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='agentrunstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('hashtags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('historical_performance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_tag'), 'hashtags', ['tag'], unique=True)
    op.create_table('keywords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_term'), 'keywords', ['term'], unique=True)
    op.create_table('model_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability', sa.Enum('LLM', 'EMBEDDINGS', 'STT', 'TTS', 'VISION', 'IMAGE_GENERATION', 'VIDEO_GENERATION', name='modelcapability'), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_configs_capability'), 'model_configs', ['capability'], unique=False)
    op.create_index(op.f('ix_model_configs_is_active'), 'model_configs', ['is_active'], unique=False)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELLED', name='scheduledjobstatus'), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_entity_id'), 'scheduled_jobs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_job_type'), 'scheduled_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_run_at'), 'scheduled_jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_status'), 'scheduled_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=150), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('decision_log', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='agenttaskstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_run_id'), 'agent_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_table('approval_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('approval_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'CANCELLED', name='approvalstatus'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_queue_entity_id'), 'approval_queue', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_queue_entity_type'), 'approval_queue', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_queue_requested_by_user_id'), 'approval_queue', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_queue_reviewed_by_user_id'), 'approval_queue', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_approval_queue_status'), 'approval_queue', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('before_data', sa.Text(), nullable=True),
    sa.Column('after_data', sa.Text(), nullable=True),
    sa.Column('audit_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('INSTAGRAM', name='platform'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_accounts_user_id'), 'social_accounts', ['user_id'], unique=False)
    op.create_table('brand_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('niche', sa.String(length=255), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('content_pillars', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('posting_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_social_account_id'), 'brand_profiles', ['social_account_id'], unique=True)
    op.create_index(op.f('ix_brand_profiles_user_id'), 'brand_profiles', ['user_id'], unique=False)
    op.create_table('content_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_brand_profile_id'), 'content_assets', ['brand_profile_id'], unique=False)
    op.create_table('content_strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche_focus', sa.String(length=255), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('content_pillars', sa.Text(), nullable=True),
    sa.Column('posting_plan', sa.Text(), nullable=True),
    sa.Column('seo_focus_keywords', sa.Text(), nullable=True),
    sa.Column('avoid_topics', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='contentstrategystatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_strategies_brand_profile_id'), 'content_strategies', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_content_strategies_status'), 'content_strategies', ['status'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_profile_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('BRAND_PROFILE', 'CONTENT_ASSET', 'POST', 'COMMENT', 'STRATEGY', 'NOTE', 'EXTERNAL', name='ragsourcetype'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('document_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_brand_profile_id'), 'rag_documents', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_source_id'), 'rag_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_rag_documents_source_type'), 'rag_documents', ['source_type'], unique=False)
    op.create_table('content_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('orientation', sa.String(length=50), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('hook_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('duplicate_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['content_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_analysis_asset_id'), 'content_analysis', ['asset_id'], unique=False)
    op.create_index(op.f('ix_content_analysis_duplicate_hash'), 'content_analysis', ['duplicate_hash'], unique=False)
    op.create_table('content_ideas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_profile_id', sa.Uuid(), nullable=False),
    sa.Column('source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['content_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_ideas_brand_profile_id'), 'content_ideas', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_source_asset_id'), 'content_ideas', ['source_asset_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_vector_id'), 'rag_chunks', ['vector_id'], unique=True)
    op.create_table('generated_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idea_id', sa.Uuid(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('media_refs', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=100), nullable=True),
    sa.Column('subtitles', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['content_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_idea_id'), 'generated_content', ['idea_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generated_content_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'FAILED', 'ARCHIVED', name='poststatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_generated_content_id'), 'posts', ['generated_content_id'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_social_account_id'), 'posts', ['social_account_id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('profile_visits', sa.Integer(), nullable=False),
    sa.Column('follows', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('raw_metrics', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_collected_at'), 'analytics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_analytics_post_id'), 'analytics', ['post_id'], unique=False)
    op.create_table('captions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('cta', sa.String(length=255), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_post_id'), 'captions', ['post_id'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=False),
    sa.Column('author_platform_id', sa.String(length=255), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('classification', sa.Enum('POSITIVE', 'NEGATIVE', 'QUESTION', 'PRODUCT_QUESTION', 'SUPPORT', 'COMPLAINT', 'SPAM', 'TROLL', 'OFF_TOPIC', 'PRAISE', 'REQUEST', 'SENSITIVE', 'UNKNOWN', name='commentclassification'), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'UNKNOWN', name='commentsentiment'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'REVIEWING', 'REPLIED', 'HIDDEN', 'IGNORED', 'ESCALATED', name='commentstatus'), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_platform_comment_id'), 'comments', ['platform_comment_id'], unique=True)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_table('content_performance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('content_format', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('hook_pattern', sa.String(length=255), nullable=True),
    sa.Column('posting_hour', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('retention_rate', sa.Float(), nullable=True),
    sa.Column('seo_score', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_performance_post_id'), 'content_performance', ['post_id'], unique=False)
    op.create_index(op.f('ix_content_performance_social_account_id'), 'content_performance', ['social_account_id'], unique=False)
    op.create_table('post_hashtags',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('hashtag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id')
    )
    op.create_table('post_keywords',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'keyword_id')
    )
    op.create_table('post_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('variant_type', sa.String(length=50), nullable=False),
    sa.Column('variant_data', sa.Text(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_variants_post_id'), 'post_variants', ['post_id'], unique=False)
    op.create_table('comment_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('platform_reply_id', sa.String(length=255), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'FAILED', name='commentreplystatus'), nullable=False),
    sa.Column('generated_by_agent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_replies_approved_by_user_id'), 'comment_replies', ['approved_by_user_id'], unique=False)
    op.create_index(op.f('ix_comment_replies_comment_id'), 'comment_replies', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_replies_platform_reply_id'), 'comment_replies', ['platform_reply_id'], unique=True)
    op.create_index(op.f('ix_comment_replies_status'), 'comment_replies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_replies_status'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_platform_reply_id'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_comment_id'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_approved_by_user_id'), table_name='comment_replies')
    op.drop_table('comment_replies')
    op.drop_index(op.f('ix_post_variants_post_id'), table_name='post_variants')
    op.drop_table('post_variants')
    op.drop_table('post_keywords')
    op.drop_table('post_hashtags')
    op.drop_index(op.f('ix_content_performance_social_account_id'), table_name='content_performance')
    op.drop_index(op.f('ix_content_performance_post_id'), table_name='content_performance')
    op.drop_table('content_performance')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_captions_post_id'), table_name='captions')
    op.drop_table('captions')
    op.drop_index(op.f('ix_analytics_post_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_collected_at'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_posts_social_account_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_generated_content_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_generated_content_idea_id'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_rag_chunks_vector_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_content_ideas_source_asset_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_brand_profile_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_content_analysis_duplicate_hash'), table_name='content_analysis')
    op.drop_index(op.f('ix_content_analysis_asset_id'), table_name='content_analysis')
    op.drop_table('content_analysis')
    op.drop_index(op.f('ix_rag_documents_source_type'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_source_id'), table_name='rag_documents')
    op.drop_index(op.f('ix_rag_documents_brand_profile_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_content_strategies_status'), table_name='content_strategies')
    op.drop_index(op.f('ix_content_strategies_brand_profile_id'), table_name='content_strategies')
    op.drop_table('content_strategies')
    op.drop_index(op.f('ix_content_assets_brand_profile_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_brand_profiles_user_id'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_social_account_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_social_accounts_user_id'), table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approval_queue_status'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_reviewed_by_user_id'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_requested_by_user_id'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_entity_type'), table_name='approval_queue')
    op.drop_index(op.f('ix_approval_queue_entity_id'), table_name='approval_queue')
    op.drop_table('approval_queue')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_run_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scheduled_jobs_status'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_run_at'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_job_type'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_entity_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_model_configs_is_active'), table_name='model_configs')
    op.drop_index(op.f('ix_model_configs_capability'), table_name='model_configs')
    op.drop_table('model_configs')
    op.drop_index(op.f('ix_keywords_term'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_hashtags_tag'), table_name='hashtags')
    op.drop_table('hashtags')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
